<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="MSI" failures="2" tests="2" name="Test5" time="0.979" errors="0" timestamp="2024-03-13T10:46:17 CDT">
  <testcase classname="api.test.DeleteUserTest" name="deleteUser" time="0.964">
    <failure type="java.lang.AssertionError" message="expected [204] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [204] but found [404]
at api.test.DeleteUserTest.deleteUser(DeleteUserTest.java:18)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- deleteUser -->
  <testcase classname="api.utilities.DataSetup" name="setup" time="0.003">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at api.utilities.DataSetup.setup(DataSetup.java:25)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- setup -->
</testsuite> <!-- Test5 -->
